#server:
#  port: 8080
#
#spring:
#  jwt:
#    header: Authorization
#    secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86G

spring:
  cloud:
    gateway:
      mvc:
        routes: # 라우팅 설정
        - id: backend-user
          predicates: # 라우팅 조건- Path=/api/user/**
          uri: lb://backend-user
          filters:
            - addAuthenticationHeader
        - id: backend-alim
          predicates: # 라우팅 조건- Path=/api/alim/**
          uri: lb://backend-alim
          filters:
            - addAuthenticationHeader
        - id: backend-post
          uri: http://k8s-backend-post-service:8080
          predicates:
            - Path=/api/post/**
          filters:
            -addAuthenticationHeader